import assert from 'node:assert/strict';
import {QUESTIONS,CATEGORIES} from './dist/data.js';
import {freshState,selectQuestions,grade,recordAnswer,calculation,blueprint,dueQuestions,validateBackup,datePlus,streak,permuteQuestion,googleReviewUrl,reviewPrompt,questionText} from './dist/engine.js';
let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name);}
test('Every authored item has valid unique answers and an explanation for each option',()=>{assert.equal(new Set(QUESTIONS.map(q=>q.id)).size,QUESTIONS.length);for(const q of QUESTIONS){assert(q.stem.length>30);assert.equal(q.options.length,q.why.length);assert.equal(new Set(q.options).size,q.options.length);assert(q.answer.length>0);assert(q.answer.every(a=>Number.isInteger(a)&&a>=0&&a<q.options.length));assert.equal(grade(q,q.answer).points,1);assert.equal(grade(q,q.answer).exact,true);assert.equal(grade(q,[]).points,0);assert(q.refs.length);}});
test('Multiple response penalizes over-selection without going below zero',()=>{const q=QUESTIONS.find(q=>q.type==='multiple');assert(grade(q,[q.answer[0]]).points>0);assert(grade(q,[q.answer[0]]).points<1);assert.equal(grade(q,q.options.map((_,i)=>i).filter(i=>!q.answer.includes(i))).points,0);assert.equal(grade(q,[q.answer[0],q.answer[0]]).points,1/q.answer.length);assert.equal(grade(q,q.options.map((_,i)=>i)).exact,false);});
test('Option shuffling preserves answer-to-rationale identity',()=>{for(const original of QUESTIONS){const q=permuteQuestion(original,'rotation');for(const a of q.answer){const old=original.options.indexOf(q.options[a]);assert(original.answer.includes(old));assert.equal(q.why[a],original.why[old]);}}});
test('Daily sets are deterministic, balanced across areas and contain no duplicate IDs',()=>{const s=freshState();const a=selectQuestions(s,{day:'2026-10-01',seed:'2026-10-01:daily'});const b=selectQuestions(s,{day:'2026-10-01',seed:'2026-10-01:daily'});assert.deepEqual(a,b);assert.equal(a.length,12);assert.equal(new Set(a.map(q=>q.id)).size,12);assert.equal(new Set(a.map(q=>q.cat)).size,8);assert.notDeepEqual(a.map(q=>q.id),selectQuestions(s,{day:'2026-10-02',seed:'2026-10-02:daily'}).map(q=>q.id));});
test('Daily sets prioritize unseen cases and space previously answered ones',()=>{const s=freshState(),first=selectQuestions(s,{seed:'day1'});for(const q of first)recordAnswer(s,q,q.answer,{confidence:'sure',sessionId:'one',now:new Date('2026-10-01T12:00:00').getTime()});const second=selectQuestions(s,{seed:'day2',day:'2026-10-02'});const repeated=second.filter(q=>first.some(x=>x.id===q.id));assert(repeated.length<=3);assert(second.some(q=>!first.some(x=>x.id===q.id)));});
test('Review dates follow 1, 3, 7, 14, 30-day intervals and errors return tomorrow',()=>{const s=freshState(),q=QUESTIONS[0];let day='2026-10-01';for(const interval of [1,3,7,14,30]){recordAnswer(s,q,q.answer,{confidence:'sure',now:new Date(day+'T12:00:00').getTime()});assert.equal(s.reviews[q.id].due,datePlus(day,interval));day=s.reviews[q.id].due;}recordAnswer(s,q,[],{now:new Date(day+'T12:00:00').getTime()});assert.equal(s.reviews[q.id].due,datePlus(day,1));assert.equal(s.reviews[q.id].success,0);assert.equal(dueQuestions(s,day).length,0);assert.equal(dueQuestions(s,datePlus(day,1)).length,1);});
test('Bookmarks, exclusions, mistakes and category filters are respected',()=>{const s=freshState(),q=QUESTIONS[0];s.bookmarks=[q.id];assert.equal(selectQuestions(s,{mode:'bookmarks'})[0].id,q.id);s.excluded=[q.id];assert.equal(selectQuestions(s,{mode:'bookmarks'}).length,0);assert(selectQuestions(s,{mode:'mixed',cat:'safety',count:8}).every(q=>q.cat==='safety'));});
test('Timed practice has 90 unique items; calculation lab has 10 unique variants',()=>{const s=freshState();for(const mode of ['exam','calculations']){const count=mode==='exam'?90:10,qs=selectQuestions(s,{mode,count,seed:'test'});assert.equal(qs.length,count);assert.equal(new Set(qs.map(q=>q.id)).size,count);}});
test('500 generated calculation variants have correct numeric grading and rounded answers',()=>{for(let i=0;i<500;i++){const q=calculation('arithmetic-'+i,i);assert(Number.isFinite(q.answer)&&q.answer>0);assert.equal(grade(q,String(q.answer)).exact,true);assert.equal(grade(q,String(q.answer).replace('.',',')).exact,true);assert.equal(grade(q,String(q.answer+1)).exact,false);assert.equal(grade(q,'').exact,false);assert.equal(grade(q,'1e3').exact,false);assert.equal(grade(q,'NaN').exact,false);assert.equal(Number(q.answer.toFixed(q.decimals)),q.answer);}});
test('Exam date selects the correct plan at the 2027 boundary',()=>{assert.equal(blueprint({examDate:'2026-12-31'}),'2022');assert.equal(blueprint({examDate:'2027-01-01'}),'2027');});
test('Backups preserve valid learning records and reject malformed history',()=>{const s=freshState(),q=QUESTIONS[0];recordAnswer(s,q,q.answer,{confidence:'sure',now:new Date('2026-10-01T12:00:00').getTime()});s.notes[q.id]='A personal note <script>alert(1)</script>';s.bookmarks=[q.id];const b=validateBackup(JSON.parse(JSON.stringify(s)));assert.equal(b.history.length,1);assert.equal(b.notes[q.id],s.notes[q.id]);assert.deepEqual(b.bookmarks,[q.id]);assert.equal(b.session,null);assert.throws(()=>validateBackup({}));assert.throws(()=>validateBackup({...s,history:[{id:'fake'}]}));assert.equal(streak(s,'2026-10-02'),1);assert.equal(streak(s,'2026-10-03'),0);});
test('External review preserves full cases, shuffled answer labels and units without learner data',()=>{const settings={province:'BC',examDate:'2026-11-15',notes:'PRIVATE_NOTE'};for(const original of [...QUESTIONS,calculation('review',4)]){const q=permuteQuestion(original,'review-test');const url=new URL(googleReviewUrl(q,settings));assert.equal(url.origin,'https://www.google.com');assert.equal(url.pathname,'/search');const query=url.searchParams.get('q');assert(query.includes(questionText(q)));assert(!query.includes('PROPOSED ANSWER'));assert(!query.includes('PRIVATE_NOTE'));const prompt=reviewPrompt(q,settings);assert(prompt.includes(q.stem));assert(prompt.includes('British Columbia'));assert(prompt.includes('PROPOSED ANSWER'));assert(!prompt.includes('PRIVATE_NOTE'));if(q.type==='numeric'){assert(prompt.includes(q.solution));assert(prompt.includes(`${q.answer} ${q.unit}`));}else{for(const i of q.answer)assert(prompt.includes(`${String.fromCharCode(65+i)}) ${q.options[i]}`));for(const why of q.why)assert(prompt.includes(why));}if(q.exhibit)assert(query.includes(q.exhibit[1].join(' | ')));}});
console.log(`${passed} engine and bank checks passed.`);
